repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v16.0.6'  # Use the sha / tag you want to point at
    hooks:
    - id: clang-format
      files: ^src/
-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
    - id: cmake-format
      files: CMakeLists.txt
